"""Generate docs/DATA_AUDIT.md from the Catalog Compiler and the SIIS normaliser (numbers are computed)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from taptrace.catalog import Catalog  # noqa: E402
from taptrace.facets import frame  # noqa: E402
from taptrace.fields import LEAK_RX  # noqa: E402
from taptrace.siis import parse_siis  # noqa: E402


def main() -> None:
    cat = Catalog(ROOT / "data" / "deeplinks.json")
    rep = cat.noise_report()
    by = {r.id: r for r in cat.rows}
    siis = json.loads((ROOT / "data" / "siis_responses.json").read_text(encoding="utf-8"))["responses"]
    qs = [l.strip() for l in (ROOT / "data" / "input.txt").read_text(encoding="utf-8").splitlines() if l.strip()]
    L = ["# Data Audit - what the provided files really contain", "",
         "Generated by `scripts/audit_report.py` from `taptrace/catalog.py` and `taptrace/siis.py`. These findings drive the design.", "",
         "## 1. deeplinks.json (Settings catalog)", "",
         f"* Declared count {rep['declared_count']}, rows {rep['rows']}, usable phone rows after quarantine **{rep['usable_phone_rows']}**, "
         f"distinct screens **{rep['screens_total']}**, screens with several control variants **{rep['screens_with_multiple_variants']}**.",
         "* URI scheme in the data is `voiceassist://masked/act/...` + `voiceassist://masked/val/...` (the PDF says `bixby://`); "
         "the only placeholder is `voiceassist://dummy_positive`.",
         f"* **TV distractors ({len(rep['tv_distractors'])})**: {', '.join(rep['tv_distractors'])}",
         f"* **Home-appliance distractors ({len(rep['iot_distractors'])})**: {', '.join(rep['iot_distractors'])}",
         f"* **Corrupt rows ({len(rep['corrupt_rows'])})**: {', '.join(rep['corrupt_rows'])} (type None, message 'Offurl'/'Onurl')",
         f"* **Exact duplicates ({len(rep['exact_duplicates'])})**: " + ", ".join(f"{a}={b}" for a, b in rep["exact_duplicates"]),
         "", "### Misleading `message` fields (why we never trust `message`)", "",
         "| Row | message | parsed object | problem |", "| :--- | :--- | :--- | :--- |"]
    for rid, msg, why in rep["misleading_messages"]:
        L.append(f"| {rid} | {msg} | {by[rid].obj} | {why} |")
    L += ["", "### Near-miss traps (closest-looking entry is the WRONG screen)", "",
          "| SIIS instruction | Naive nearest entry | Why wrong | TapTrace |", "| :--- | :--- | :--- | :--- |",
          "| Factory data reset | DL-0022 'auto factory reset' | resets after failed unlocks - a different screen | `dummy_positive` |",
          "| Restart your phone | DL-0124 / 0419 / 0479 (inactivity / scheduled / auto restart) | configures auto-restart, does not restart | no deeplink (power-button action) |",
          "| Auto rotate | DL-0461 'rotate to landscape' | Home-screen setting only | `dummy_positive` |",
          "| Safe mode / Software update / Clear cache | (none exists) | - | `dummy_positive` or null |",
          "| Put unused apps to sleep | DL-0560 'Battery' (parent menu) | parent-menu match (PDF 6.2) | DL-0417 (leaf, on) |", "",
          "## 2. siis_responses.json (knowledge)", "",
          "| Line | SIIS id | Document title | Complaint facets | Doc facets | Leak-bearing sentences | Corrupt sentences |",
          "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |"]
    for i, (q, r) in enumerate(zip(qs, siis), 1):
        d = parse_siis(r["siis_response"])
        cf = frame(q)
        leaks = sum(x.leak for s in d.sections for x in s.sentences)
        corrupt = sum(x.corrupt for s in d.sections for x in s.sentences)
        L.append(f"| {i} | {r['id']} | {d.title} | {sorted(cf.symptoms)} {sorted(cf.contexts)} | "
                 f"{sorted(d.title_frame.symptoms)} {sorted(d.title_frame.contexts)} | {leaks} | {corrupt} |")
    raw = json.dumps(siis)
    L += ["", f"* Ids run row_1..row_22 with **row_6 and row_18 absent**; 20 records, 11 unique documents.",
          f"* Link/e-mail patterns found by the zero-leak regex inside 'pre-cleaned' SIIS text: {len(LEAK_RX.findall(raw))} "
          "(e.g. an e-mail address in the Kids-PIN section), plus 'check out our website' / 'provided links' phrasing.",
          "* Every content field starts with a product-category prefix (`Smartphone,Others Mobile,... Title ( ... ):`) that is stripped.",
          "* Several documents are the wrong document for their complaint (Multi-window for a dark tablet or a floating menu; TV "
          "mirroring for a small phone screen; camera-video flicker for a Fold that flickers when opened) - handled by the Relevance Gate.",
          "* All 20 complaints are Display-domain although the PDF names Battery / Camera / Performance too - the mapping benchmark "
          "therefore covers all domains (`eval/mapping_benchmark.json`)."]
    (ROOT / "docs" / "DATA_AUDIT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
